### ISSUE TITLE
[ALM Accelerator] FYI - Unable to find pipeline caching scopes

### ISSUE THREAD

**Issue by dmcweeney** [microsoft/coe-starter-kit#2220]
### What is your question?

Just an FYI as I am sure someone else will encounter the same problem.

I just encountered a problem with the Post-job: Cache Powershell Modules failing with the following error buried in the stack trace.

System.ArgumentException: Unable to find pipeline caching scopes.

I had changed my pipeline multi-stage pipeline and the deployment stage used a deployment job like:

```
- stage: DeployTo
  jobs:
  - deployment: DeployTo
    pool:
      vmImage: 'windows-2022'
    strategy:
      runOnce:
        deploy:
          steps:

```

After a bit of searching it turns out the CacheV2 task does not like deployment jobs - see https://github.com/microsoft/azure-pipelines-tasks/issues/13420 for details.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

latest
