### ISSUE TITLE
[ALM Accelerator - BUG]: Production Pipeline Is Not Getting Triggered Automatically

### ISSUE THREAD

**Issue by shree2905** [microsoft/coe-starter-kit#2935]
### Describe the issue

**Overview of the Environment:**
I've three deployment environment configured in deployment profile i.e. Validation, Test and Prod. In deployment profile the target branch kept as "[Use Solution Branches]".

![image](https://user-images.githubusercontent.com/79618656/172407336-0905a3c6-360e-4d2d-b959-3b612d7d1dc8.png)

![image](https://user-images.githubusercontent.com/79618656/172407481-76e28d4d-5402-4b38-8cda-610514961d30.png)

![image](https://user-images.githubusercontent.com/79618656/172413017-4cfbb639-f72d-43e8-9ca1-90d8830bf1a1.png)

When I click on the "DEPLOY SOLUTION" the validation pipeline get's triggered. After completion of PR request to solution branch test pipeline gets triggered. While deploying the solution if I create PR from the solution branch to the main branch  which my default branch, it's not triggering solution to deploy into prod.

**Questions:**
1. Is there anything that I have to change in order to trigger the (deploy-prod-SolutionName) pipeline automatically.  
2. When I commit a solution two branches gets created one with solution name having YAML files and other with the name as (username-solution_name) having solution Packages. while deploying which should be the source branch and target branch.
3. After the PR merge how to delete the created branches automatically. Branch policies doesn't let to delete the branches.

### Expected Behavior

deploy-prod-SolutionName pipelineshould trigger automatically without any manual configuration. 

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

April 2022

### Steps To Reproduce

1.Click on the "Deploy Solution" Button in AA4pp App, selected the Source Branch and Target Branch.
2.Now Clicked on Deploy Solution Button.
3.Click on Processing icon --> Navigates to Azure Devops, After the successful completion of Pipeline go to pull requests
4.Approve the PR and click on the complete the merge, Now Test and Prod should trigger automatically.

**Comment by mikefactorial** [comment]
@shree2905 thanks for the detailed description of the issue. Assuming that your default branch is "main" and not "master" or some other name the only thing I can think of is there are no changes being pushed as part of the PR in to the SolutionPackage folder. If you look at the triggers on the pipeline you'll see that by default we are triggering based on a branch called "main" and changes to any of the folders SolutionPackage, Plugins, WebResources in the pipeline

```
trigger:
  branches:
    include:
    # Replace the following with actual branch name(s) in your repo for which you want to trigger a build. The assumption here is that you only want to only trigger on a change to a specific branch rather than a change on any branch which would include your working branch for development.'
    - main
  paths:
# Replace 'SolutionFolderInBranch' with actual folder name in repo (i.e. this will be the folder that contains your unpacked solution. In the case where you are using a repo per solution you may not need to specify this value)
    include: # Add any additional paths to include (e.g. SampleSolutionName/PCFControls etc.)
    - SampleSolutionName/SolutionPackage/ # Replace SolutionFolder with actual folder name in repo
    - SampleSolutionName/Plugins/ # Replace SolutionFolder with actual folder name in repo
    - SampleSolutionName/WebResources/ # Replace SolutionFolder with actual folder name in repo
```
That would be the first thing to check.
