### ISSUE TITLE
Run Power Apps Test Automation Tests via Chrome

### ISSUE THREAD

**Issue by almpocahb** [microsoft/coe-starter-kit#3814]
### Describe the issue

I had setup ALM Accelerator manually following the steps that mentioned here (https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform) and currently I am facing this issue while trying to approve the pull request 
![image](https://user-images.githubusercontent.com/114581811/193246065-d8cd0bb0-d522-4721-89c5-bb4cd108afc3.png)
![image](https://user-images.githubusercontent.com/114581811/193246073-bc583a09-8ca2-433e-b5c2-3bb347aba994.png)
 
**Note** I have created test solution for the testing purpose and it contains one workflow and one web-resource file and the issue is not always occurring

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.0.3

### Steps To Reproduce

1. Open ALM Accelerator App
2. Select the solution
3. Commit the solution
4. deploy the solution
5. Go to Azure DevOps and select the repo then pull request
6. Open the created request to Approve

**Comment by mikefactorial** [comment]
@almpocahb assuming you have set the following values in the global variable group? If so my best guess is that there are some special characters being passed in to the overrideTestrunParameters parameter in the following that aren't being encoded correctly e.g. most likely a ' in on the parameters. Mind confirming this and will look into the best way to fix this issue.

```
- task: VSTest@2 # Only running chrome tests for now since Power Apps is already cross browser.  These test are for UI / Integration testing.  Can revisit if we discover we need cross browser later.
  displayName: "Run Power Apps Test Automation Tests via Chrome"
  condition: and(succeeded(), eq(variables.RunTests, 'true'), eq(variables.PrOrOverride,'true'))
  inputs:
    testAssemblyVer2: '$(CanvasTestFrameworkPath)\Microsoft.PowerApps.TestAutomation.Tests.dll'
    testFiltercriteria: "TestCategory=PowerAppsTestAutomation"
    uiTests: true
    runSettingsFile: '$(CanvasTestFrameworkPath)\patestautomation.runsettings'
    overrideTestrunParameters: '-OnlineUsername ${{ parameters.testAccountUsername }} -OnlinePassword ${{parameters.testAccountPassword}} -BrowserType "Chrome" -OnlineUrl ${{ parameters.makerPortalUrl }} -UsePrivateMode true -TestAutomationURLFilePath "$(JsonPath)" -DriversPath $(ChromeWebDriver) -LoginMethod ${{ parameters.loginMethod }}'
    testRunTitle: "Run Power Apps Test Automation Tests via Chrome"
  continueOnError: false
```


Name | Value
-- | --
TestAutomationLoginMethod | CloudIdentity
TestAutomationMakerPortalUrl | The URL from the Power Apps maker portal, typically https://make.powerapps.com
TestAutomationUsername | The user account used to execute the automated tests.
TestAutomationPassword | The password for the user account to execute the automated tests.
