### ISSUE TITLE
[ALM Accelerator - Feature] "Rerun failed jobs" issue: Please include an Artifact Cleanup step in the deployment pipeline before publishing artifacts.

### ISSUE THREAD

**Issue by Reinhard-S** [microsoft/coe-starter-kit#4842]
### Is your feature request related to a problem? Please describe.

Hello,

Could you please consider adding an additional step to remove any pre-existing artifacts before creating and publishing Artifacts in commit- and deployment pipelines?

This might be a convenience request but it still adds value and saves time if someone clicked at Rerun by mistake:
Makers should be able to rerun failed deployment pipeline jobs in case of minor issues, e.g. because activation of Flows failed. In such cases it is not possible to simply rerun the failed job because artifacts already exists from the failed execution.

Error Message returned by step Publish Artifacts: Artifact drop already exists for build.
ALM Accelerator version currently in use: February 2023; 1.0.20230206.1

Thank you,
Reinhard

### Describe the solution you'd like

If a maker tries to rerun a failed job the original error will be disguised by the artifact publishing issue. I'd suggest to alter the pipelines in a way that rerunning a failed job always throws the same error that initially occurred, also because of documentation purposes.

### Describe alternatives you've considered

Makers need to be trained to select "Run new" instead of "Rerun".
This keeps the log containing the original error within the Runs of a pipeline.

Drawback:
Makers might still click at Rerun by mistake (especially inexperienced / new team members) and then it is no longer possible to see the original issue the pipeline job had unless a new job is scheduled afresh which takes time until it completes.

**Comment by mikefactorial** [comment]
@Reinhard-S will look into the feasibility of this. The last time we looked at this we couldn't find a way to make it work, but appreciate you bringing up the suggestion again.

**Comment by Reinhard-S** [comment]
Hi @mikefactorial,

Apologizes, I was not aware that you previously already looked into the issue. Seems to be a common issue though, the discussion here was quite interesting to read for me:
https://github.com/MicrosoftDocs/azure-devops-docs/issues/6677

Maybe the very last suggestion in that thread from @bbattha to is feasible? 

```
# Use Conditional with two Tasks with different Artifact names to manage failure cases allowing for successful retry - (artifacts are immutable)
- task: PublishPipelineArtifact@1
  displayName: 'Publish Successful E2E Artifacts'
  condition: succeeded()
  inputs:
    targetPath: './Artifacts/E2ESrc_withLastRunResults.zip'
    artifact: 'E2EArtifacts'
    publishLocation: 'pipeline'
   
- task: PublishPipelineArtifact@1
  displayName: 'Publish Failed E2E Artifacts'
  condition: not(succeeded())
  inputs:
    targetPath: './Artifacts/E2ESrc_withLastRunResults.zip'
    artifact: E2EArtifacts-Attempt#$(System.JobAttempt)
    publishLocation: 'pipeline'
```

The only issue I see is that we obviously are depending on follow-up actions within the pipeline which do not really depend on the artifacts published earlier. Steps like activating Flows could potentially fail but maybe moving the publishing step at the end of the pipeline could solve this.

Thanks!

Cheers,
Reinhard
