### ISSUE TITLE
[ALM Accelerator - BUG]: "Could not get the latest source version for repository" during pull request

### ISSUE THREAD

**Issue by sefa-phaag** [microsoft/coe-starter-kit#5004]
### Describe the issue

I created a new pull request to merge code into my solution branch (SEFACustomConnectors) and the deploy-validation-SEFACustomConnectors pipeline kicked off but failed almost immediately with the following error: "/SEFACustomConnectors/deploy-validation-SEFACustomConnectors.yml: Could not get the latest source version for repository coe-alm-accelerator-templates hosted on Azure Repos using ref refs/heads/master." No logs were generated.

I haven't changed any of the pipeline files and this is the entirety of my deploy-validation-SEFACustomConnectors.yml file:

```yaml
#You can use this sample template if you plan to store the pipeline templates in one repo and your pipeline YAML in another. This is useful for when you have multiple repos and don't want to maintain the templates in multiple places.'
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: git
    ref: master  # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    name: Power Apps Solutions/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/Power Apps Solutions/coe-alm-accelerator-templates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
trigger:
  branches:
    include:
    # Replace the following with actual branch name(s) in your repo for which you want to trigger a build. The assumption here is that you only want to only trigger on a change to a specific branch rather than a change on any branch which would include your working branch for development.'
    - SEFACustomConnectors
  paths:
# Replace 'SolutionFolderInBranch' with actual folder name in repo (i.e. this will be the folder that contains your unpacked solution. In the case where you are using a repo per solution you may not need to specify this value)
    include: # Add any additional paths to include (e.g. SEFACustomConnectors/PCFControls etc.)
    - SEFACustomConnectors/SolutionPackage/ # Replace SolutionFolder with actual folder name in repo
    - SEFACustomConnectors/Plugins/ # Replace SolutionFolder with actual folder name in repo
    - SEFACustomConnectors/WebResources/ # Replace SolutionFolder with actual folder name in repo
    
name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

# NOTE: If you want to use different values for these variables, you can remove the variable group and attach them directly to this pipeline. The group specified below is a variable group defined in the Library for the Pipelines
variables:
- group: alm-accelerator-variable-group
- name: SolutionName
  value: 'SEFACustomConnectors' #Replace with the actual name of the solution you are building. (NOTE: Not the Display Name)

stages:
- template: Pipelines\Templates\build-deploy-Solution-To-Environment.yml@PipelineRepo #The @PipelineRepo tells the pipeline where to look for the templates based on the name of the repo you specified above
```

Looking at this, I believe the issue is that the ref is "master" but the coe-alm-accelerator-templates branch is actually called "main". I think this is similar to #3502, but kind of the other way around. My template repo was created with the main branch, but my solution-specific files are referring to master.

The deploy-validation-SEFACustomConnectors pipeline was created using the February 23 release, but I have since updated to the March 23 release and synced the pipeline repo.

Even if I am right about the problem, I'm not sure what the correct way to fix it is, considering that the SEFACustomConnectors branch requires a pull request to make changes and the pull request is failing...

Full disclosure, I didn't really understand how to set this up correctly in the first place, so I'm actually trying to merge from master to SEFACustomConnectors just by using a pull request in Azure DevOps. With my original commit, I went directly to master because I was just committing it to source control and not actually making a change. At the moment, master has my solution files, but SEFACustomConnectors has the build templates.

### Expected Behavior

The pipeline should execute without errors.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

March 2023

### Steps To Reproduce

1. Create a pull request targeting the solution branch.

**Comment by sefa-phaag** [comment]
Update: I was able to fix this problem by changing the ref from "master" to "main" and then checking in the code directly (no pull request) by temporarily turning off the Build Validation branch policy on SEFACustomConnectors, but I still think it's an issue that the ref was wrong to begin with.

**Comment by mikefactorial** [comment]
@sefa-phaag can you check the default branch name for repos in the project under Project Settings to see if that may be the problem? 
![image](https://user-images.githubusercontent.com/42348035/225420279-3ca03855-6792-40c4-9aa0-7c259d424d8f.png)

**Comment by sefa-phaag** [comment]
That setting is off. My screen looks exactly the same as yours.

**Comment by mikefactorial** [comment]
Reading through this again it sounds like you're not following the guidance for how to commit the solution for the first time. You should be creating a feature branch (New Branch) based on main (Based On). Which is likely why things are out of sync. This is generally the default options that show up in the commit dialog when you commit for the first time e.g.

![image](https://user-images.githubusercontent.com/42348035/225423995-9cc50941-0def-4f43-8ad0-8f3d7f034980.png)

**Comment by sefa-phaag** [comment]
I have two repos. coe-alm-accelerator-templates was created by the project setup wizard and has a main branch. SEFA Custom Connectors I created manually as a place to store my source code - it never had  a main branch. I just created a new one in Azure Dev Ops and it created a master branch for me (it didn't ask me for a name). When I committed the solution initially, I chose master instead of creating a new branch, which I agree was wrong, but my Based On option would've been "master" and not "main". Moreover, is there some sort of dependency between the repos? The ref is wrong when it's pointing at coe-alm-accelerator-templates, which I believe I did set up correctly and always had a main branch; not master.

**Comment by sefa-phaag** [comment]
It does appear to me that something about the solution commit is pulling the DevOps server-level "default" branch, which appears to be "master" even though I don't have that set anywhere. The problem is that the coe-alm-accelerator-templates aren't saved to the default branch, but the process creating the solution-specific templates still thinks they are. To be clear "main" *is* the default branch in the coe-alm-accelerator-templates repo (there is no master branch).

**Comment by sefa-phaag** [comment]
Another odd thing on this is that in deploy-prod-SEFACustomConnectors, *both* the ref and trigger branch are wrong (they are backwards):

```yaml
#You can use this sample template if you plan to store the pipeline templates in one repo and your pipeline YAML in another. This is useful for when you have multiple repos and don't want to maintain the templates in multiple places.'
resources:
  repositories:
  - repository: PipelineRepo  # repository name (DO NOT CHANGE THIS VALUE) 
    type: git
    ref: master  # If your pipeline templates are in a branch other than the default branch specify the branch here. Otherwise the default branch will be used by default.
    name: Power Apps Solutions/coe-alm-accelerator-templates  #This is the name of the repo in the current project in Azure Devops that has the pipeline templates. If the repo is in a different project you can specify the project and repo using the format ProjectContainingTheBuildTemplates/Power Apps Solutions/coe-alm-accelerator-templates (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#type)
trigger:
  branches:
    include:
    # Replace the following with actual branch name(s) in your repo for which you want to trigger a build. The assumption here is that you only want to only trigger on a change to a specific branch rather than a change on any branch which would include your working branch for development.'
    - main
  paths:
# Replace 'SolutionFolderInBranch' with actual folder name in repo (i.e. this will be the folder that contains your unpacked solution. In the case where you are using a repo per solution you may not need to specify this value)
    include: # Add any additional paths to include (e.g. SEFACustomConnectors/PCFControls etc.)
    - SEFACustomConnectors/SolutionPackage/ # Replace SolutionFolder with actual folder name in repo
    - SEFACustomConnectors/Plugins/ # Replace SolutionFolder with actual folder name in repo
    - SEFACustomConnectors/WebResources/ # Replace SolutionFolder with actual folder name in repo
    
name: 1.0.$(Date:yyyyMMdd)$(Rev:.r)

# NOTE: If you want to use different values for these variables, you can remove the variable group and attach them directly to this pipeline. The group specified below is a variable group defined in the Library for the Pipelines
variables:
- group: alm-accelerator-variable-group
- name: SolutionName
  value: 'SEFACustomConnectors' #Replace with the actual name of the solution you are building. (NOTE: Not the Display Name)

stages:
- template: Pipelines\Templates\build-deploy-Solution-To-Environment.yml@PipelineRepo #The @PipelineRepo tells the pipeline where to look for the templates based on the name of the repo you specified above
```
