### ISSUE TITLE
[ALM Accelerator - BUG]: Value cannot be null - Parameter name: securityNamespace

### ISSUE THREAD

**Issue by ZantioIT** [microsoft/coe-starter-kit#5856]
### Describe the issue

I'm new to using ALM accelerator, but i've succesfully set it up on your own tenant and wanted to set it up on a customers tenant. But when I try to do my first commit i get this error.

![image](https://github.com/microsoft/coe-starter-kit/assets/97155760/1e72e305-e688-4c71-93c8-e2722a4a5790)

I tried to set this up on a self-hosted agent pool and thought that was the reason for error, but i've moved back to Microsoft hosted and I get the same error.

### What component are you experiencing the issue with?

ALM Accelerator Pipelines

### What solution version are you using?

1.0.20230606.1

**Comment by mikefactorial** [comment]
@ZantioIT this looks to be a policy at the organization level of the Azure DevOps instance there are likely extensions installed that run on Pre or Post Build that are expecting some parameter or variable to be specified. There's nothing in the ALM Accelerator pipelines that would cause this issue. A quick search on the error does produce a few results in other GitHub repos that may help https://github.com/MicrosoftDocs/azure-devops-docs/issues/8146

**Comment by mikefactorial** [comment]
I wonder if you may be able to troubleshoot by looking at other pipelines in the customer's organization to see if there's some specific cache task parameters not in our default pipeline templates.

**Comment by mikefactorial** [comment]
There's an active (but closed) issue on the docs GitHub site related to this https://github.com/microsoft/azure-pipelines-tasks/issues/11291. I've yet to find any answers, however, as to why some organizations are reporting this but others aren't.

**Comment by mikefactorial** [comment]
@ZantioIT / @tkudya could one of you rerun the failed pipeline with Enable system diagnostics turned on and provide the logs of the pipeline run? 
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/463ccf9d-30e4-4826-9e7b-634b357fbe1f)
![image](https://github.com/microsoft/coe-starter-kit/assets/42348035/459a01e6-6af0-4ffe-8891-c4d7f5a42dfb)

**Comment by mikefactorial** [comment]
Also, can you try the following since I'm not able to replicate this issue on my end? 

Update the cache task in the export pipeline template export-Solution.yml (https://github.com/microsoft/coe-alm-accelerator-templates/blob/main/Pipelines/Templates/export-Solution.yml) to include 

```
    securityNamespace: cache
```

as an input.

Example: 
```
# Restore PowerShell Module dependencies if available in cache
# https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops
- task: Cache@2
  displayName: Cache Powershell Modules
  inputs:
    key:  restoremodules | "$(powerPlatformToolsSubPath)" | $(Pipeline.Workspace)/PipelineUtils/Pipelines/Templates/install-powershell-modules.yml
    path: $(powerPlatformToolsPath)
    cacheHitVar: powerPlatformToolsPath_IsCached
    securityNamespace: cache
  condition: and(succeeded(), ne(variables['CacheEnabled'], 'false'))
```
