### ISSUE TITLE
[ALM Accelerator - QUESTION] deploy-solution-import-pre-hook.yml 

### ISSUE THREAD

**Issue by lingutla123** [microsoft/coe-starter-kit#6434]
### What is your question?

HI Mike

In the prehook, we are able to populate the $parameters value in below code and also getting ServiceConnectionName value, however not able to read the ServiceConnectionName  value in the back up task (trying to take backup the environment). Getting below error:

![image](https://github.com/microsoft/coe-starter-kit/assets/126264610/b55e5270-4589-4008-aa30-4c3c40c86a3e)

   - powershell: |
        # load PowerShell files into memory
        . "$env:POWERSHELLPATH/load-save-pipeline-parameters.ps1"
        $parameters = Read-Pipeline-Parameters "$(Agent.BuildDirectory)\deploy-pipeline-parameters.json"
        
        if($parameters.serviceConnectionName -Match "qa"){Write-Host $parameters.serviceConnectionName} 
      displayName: 'Backup Environment'

    - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.backup-environment.PowerPlatformBackupEnvironment@2
      displayName: 'Power Platform Backup Environment'
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: '${{parameters.serviceConnectionName}}'
        BackupLabel: 'Full backup - $(Build.BuildNumber)'

### What component are you experiencing the issue with?

ALM Accelerator Canvas App

### What solution version are you using?

August 2023

**Comment by mikefactorial** [comment]
@lingutla123 the parameters are only in the scope of the Powershell step in this case. You can write the serviceConnectionName parameter to a variable to use in the following task using e.g.

```
Write-Host "##vso[task.setvariable variable=myServiceConnectionNam]$parameters.serviceConnectionName"
```
and then 

```
- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.backup-environment.PowerPlatformBackupEnvironment@2
  displayName: 'Power Platform Backup Environment'
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: '$(myServiceConnectionNam)'
    BackupLabel: 'Full backup - $(Build.BuildNumber)'
```
